<?xml version="1.0" encoding="utf-8"?><Database Name="RechargeGauntlet" Class="RechargeGauntletDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5GQ0AGD;Initial Catalog=RechargeGauntlet;Integrated Security=True" SettingsObjectName="RechargeGauntlet.Properties.Settings" SettingsPropertyName="RechargeGauntletConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PhoneBook" Member="PhoneBooks">
    <Type Name="PhoneBook">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MobileNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_PhoneBook" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recharge" Member="Recharges">
    <Type Name="Recharge">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Transaction_id" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Recharge" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Request" Member="Requests">
    <Type Name="Request">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SMSBank" Member="SMSBanks">
    <Type Name="SMSBank">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sender" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="stime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SMSType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SMSType_SMSBank" Member="SMSType" ThisKey="SMSType_id" OtherKey="Id" Type="SMSType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SMSType" Member="SMSTypes">
    <Type Name="SMSType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="SMSType_SMSBank" Member="SMSBanks" ThisKey="Id" OtherKey="SMSType_id" Type="SMSBank" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="User_PhoneBook" Member="PhoneBooks" ThisKey="Id" OtherKey="User_Id" Type="PhoneBook" />
      <Association Name="User_Recharge" Member="Recharges" ThisKey="Id" OtherKey="User_Id" Type="Recharge" />
    </Type>
  </Table>
</Database>